### ISSUE TITLE
iframe resizer might be broken on brave

### ISSUE THREAD

**Issue by pgrm** [apaleo/oss-traces#157]
Traces on brave with ad-block disabled, after loading enough traces, it got stuck this way:

![image](https://user-images.githubusercontent.com/713456/83653817-8c082480-a5bc-11ea-83dc-bf56026bad34.png)

**Comment by haydar-metin** [comment]
what are "enough traces" in numbers :)

**Comment by pgrm** [comment]
this is on the property view - the height was fixed to the initial 920px and didn't grow beyond that - I think the issue is that https://github.com/apaleo/oss-traces/blob/76dd47f1109075cf0f121101698a74511ef0fc49/src/Traces.Web/wwwroot/css/layout.css#L11 should be `min-height` maybe?
