### ISSUE TITLE
Traces UI Integration doesn't work in Brave browser

### ISSUE THREAD

**Issue by pgrm** [apaleo/oss-traces#22]
the apaleo One UI integration (iframe) doesn't work in the brave browser, when it is configured to block cross-site cookies. Allowing all cookies fixes that issue, but that's something that we should tackle in the future

Update: Also the list of traces isn't displayed in brave

**Comment by pgrm** [comment]
more details - it now works with brave shield down. With brave shield up, I can see a 500 on POST https://traces.herokuapp.com/signin-apaleo

all other calls to traces work correctly

**Comment by pgrm** [comment]
A customer mentioned that it's also broken on iOS devices, might be related

**Comment by haydar-metin** [comment]
it fails because brave shield blocks cross site cookies and so the application fails to authenticate because a cookie is missing so it throws an exception

**Comment by pgrm** [comment]
@haydar-metin can we somehow overcome this issue? - like not use cross site cookies?

**Comment by haydar-metin** [comment]
@pgrm tbh, i didnt really check the code about authentication in full detail, maybe we can, maybe we can not

maybe @randyrod has some insight / idea how to overcome this

**Comment by randyrod** [comment]
I'll do some digging and see if I find anything. Because I personally do not know as of right now.

**Comment by ozonni** [comment]
Duplicate
