### ISSUE TITLE
Traces return bad request 400 if the access token is too big

### ISSUE THREAD

**Issue by bennetone** [apaleo/oss-traces#245]
With all the roles being encoded in the token the access token can get quite big. Seems like traces does not like such big tokens and then shows a 400 bad request.

**Comment by bennetone** [comment]
one of the multiple zendesk tickets: https://apaleo.zendesk.com/agent/tickets/4071

**Comment by randyrod** [comment]
Issue moved to [apaleo/identity #1382](https://github.com/apaleo/identity/issues/1382) via [**ZenHub**](https://www.zenhub.com/)
