### ISSUE TITLE
Upgrade database for traces app

### ISSUE THREAD

**Issue by bennetone** [apaleo/oss-traces#261]
https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases?c=&utm_campaign=postgreslimits&utm_medium=telex&utm_source=nurture&utm_content=devcenter&utm_term=upgrade#upgrading-with-pg-copy

Should we maybe also consider to have a clean-up mechanism that deleted traces older than 3 months or sth ...?

**Comment by randyrod** [comment]
Migration was made to hobby-basic plan 9 eur monthly with a limit of 10m rows. To this date 18/11/2020 we are at 9.3k rows.

**Comment by randyrod** [comment]
Old DB has been deleted and the app is working nice and stable 😃
